CC = g++
target1 = p2
target2 = p4
target3 = p7
target4 = p8
CFLAGS = -Wall -g -O3 -std=c++11

all: *.cpp
	$(CC) $(CFLAGS) -o $(target1) $(target1).cpp
	$(CC) $(CFLAGS) -o $(target2) $(target2).cpp
	$(CC) $(CFLAGS) -o $(target3) $(target3).cpp
	$(CC) $(CFLAGS) -o $(target4) $(target4).cpp

#reference : https://hackmd.io/s/SySTMXPvl