CC = g++
target1 = p3
target2 = p7
target3 = p8
target4 = p9
target5 = p14
target6 = p17
CFLAGS = -Wall -g -O3 -std=c++11

all: *.cpp
	$(CC) $(CFLAGS) -o $(target1) $(target1).cpp
	$(CC) $(CFLAGS) -o $(target2) $(target2).cpp
	$(CC) $(CFLAGS) -o $(target3) $(target3).cpp
	$(CC) $(CFLAGS) -o $(target4) $(target4).cpp
	$(CC) $(CFLAGS) -o $(target5) $(target5).cpp
	$(CC) $(CFLAGS) -o $(target6) $(target6).cpp

#reference : https://hackmd.io/s/SySTMXPvl