CC = g++
target1 = p1
target2 = p5
target3 = p10
target4 = p11
target5 = p13
CFLAGS = -Wall -g -O3 -std=c++11

all: *.cpp
	$(CC) $(CFLAGS) -o $(target1) $(target1).cpp
	$(CC) $(CFLAGS) -o $(target2) $(target2).cpp
	$(CC) $(CFLAGS) -o $(target3) $(target3).cpp
	$(CC) $(CFLAGS) -o $(target4) $(target4).cpp
	$(CC) $(CFLAGS) -o $(target5) $(target5).cpp

#reference : https://hackmd.io/s/SySTMXPvl