cc = g++
flags = -Os -O3 -std=c++11 -Wall -o 
target1 = p4
target2 = p6
target3 = p8

all: *.cpp
	$(cc) $(flags) $(target1) $(target1).cpp
	$(cc) $(flags) $(target2) $(target2).cpp
	$(cc) $(flags) $(target3) $(target3).cpp