CC = g++
target1 = p6
target2 = p8
target3 = p13
CFLAGS = -Wall -g -O3 -std=c++11

all: *.cpp
	$(CC) $(CFLAGS) -o $(target1) $(target1).cpp
	$(CC) $(CFLAGS) -o $(target2) $(target2).cpp
	$(CC) $(CFLAGS) -o $(target3) $(target3).cpp

#reference : https://hackmd.io/s/SySTMXPvl