cc = g++
flags = -std=c++11 -Wall -O3 -Os -o

target1 = p1
target2 = p3
target3 = p4
target4 = p8

all: *.cpp
	$(cc) $(flags) $(target1) $(target1).cpp
	$(cc) $(flags) $(target2) $(target2).cpp
	$(cc) $(flags) $(target3) $(target3).cpp
	$(cc) $(flags) $(target4) $(target4).cpp
